version: '3.8'
services:
  postgres:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - blogdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    container_name: 'flask-blog'
    env_file:
      - ./.env
    volumes:
      - .:/blogflask
    command: >
      /bin/sh -c "flask --app run db upgrade
      && gunicorn --bind 0.0.0.0:5000 run:app"
    ports:
      - 5000:5000
    depends_on:
      - postgres

volumes:
  blogdb:
    external: True