version: '3.8'
services:
  postgres:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - blogdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    container_name: 'flask-blog'
    env_file:
      - ./.env
    volumes:
      - .:/blogflask
    depends_on:
      - postgres
  app_migrate:
    extends:
      service: 'app'
    container_name: 'flask-migrate'
    command: >
      /bin/sh -c "flask --app run db upgrade"
  app_run:
    extends:
      service: app
    container_name: 'flask-run'
    command: gunicorn --bind 0.0.0.0:5000 run:app
    ports:
      - 5000:5000

volumes:
  blogdb:
    external: True